### ISSUE TITLE
Calling the API 

### ISSUE THREAD

**Issue by adesinah** [benjojo/bpm#2]
Hi.
Thanks for making this awesome package. I don't much about how BPM is obtained. Is it possible to have this API accepts an audio file (like method/function with a parameter) and returns its BPM? In other words, I do not want to use the CMD interface.

Thanks.

**Comment by benjojo** [comment]
Sure, there is nothing stopping you from writing a HTTP wrapper around this, just use it as a library instead: https://godoc.org/github.com/benjojo/bpm

Depending on the formats coming in, you will need to transcode the inputs into raw samples before handing them over to the functions

**Comment by D-sense** [comment]
@benjojo, thank you for your reply (and your patience).
This is what my main() looks like:

```
func main(){
        file, err := os.Open("../test_tracks/f.mp3")
	if err != nil {
		log.Fatal(err)
	}

	byteFile:= streamToByte(file)

	floatFile := Float64frombytes(byteFile)

	bpm.ReadFloatArray(floatFile)

	fmt.Printf("%f\n", bpm.ScanForBpm(floatFile, *min, *max, 1024, 1024))
}

func streamToByte(stream io.Reader) []byte {
	buf := new(bytes.Buffer)
	buf.ReadFrom(stream)
	return buf.Bytes()
}

func Float64frombytes(bytes []byte) []float32 {
	result  := make([]float32, 1)

	bits := binary.LittleEndian.Uint32(bytes)
	float := math.Float32frombits(bits)
	result = append(result, float)

	return result
}

``` 

The concern is that, I seem to be getting the same BPM for all audio tracks I have inputted.

**Comment by adesinah** [comment]
@benjojo, thank you for your reply (and your patience).
So, if I convert the file (i.e., mp3) to pcm_s16le (WAV), I should be able to pass it to the function and get accurate result?

Currently, I am not converting the file to raw sample (i.e., pcm_s16le etc). This is what my main() looks like:

```
var (
	min                 = flag.Float64("min", 40, "min BPM you are expecting")
	max                 = flag.Float64("max", 200, "max BPM you are expecting")
)

func main(){
        file, err := os.Open("../test_tracks/f.mp3")
	if err != nil {
		log.Fatal(err)
	}

	byteFile:= streamToByte(file)

	floatFile := Float64frombytes(byteFile)

	bpm.ReadFloatArray(floatFile)

	fmt.Printf("%f\n", bpm.ScanForBpm(floatFile, *min, *max, 1024, 1024))
}

func streamToByte(stream io.Reader) []byte {
	buf := new(bytes.Buffer)
	buf.ReadFrom(stream)
	return buf.Bytes()
}

func Float64frombytes(bytes []byte) []float32 {
	result  := make([]float32, 1)

	bits := binary.LittleEndian.Uint32(bytes)
	float := math.Float32frombits(bits)
	result = append(result, float)

	return result
}

``` 

With this approcach, I seem to be getting the same BPM for different audio tracks I have inputted.

**Comment by benjojo** [comment]
From a glance that looks fine, but the conversion to pcm_s16le is critical, nothing will work if that is not done.

**Comment by adesinah** [comment]
Please is there a package you can recommend for the conversion (pcm_s16le)? I can't seem to find anything helpful.

**Comment by adesinah** [comment]
This has been resolved. Thanks @benjojo.
