### ISSUE TITLE
Get first/last beat time.

### ISSUE THREAD

**Issue by itzTheMeow** [benjojo/bpm#5]
With this library is there a way to get the first and/or last beat timestamp? Meaning the timestamp in the audio file where the first beat is counted as it might not be at 0:00.

**Comment by itzTheMeow** [comment]
@benjojo

**Comment by itzTheMeow** [comment]
does that mean no :laughing:

**Comment by benjojo** [comment]
You are more than welcome to implement it and submit a PR, but I am not
current working on this library as I am not dealing with any audio stuff as
part of my current job obligations
